image: golang:1.10

verify:
  script:
  - make verify

.test_template: &test_definition
  services:
    - name: registry.gitlab.com/gitlab-org/build/cng/gitaly:latest
      # Disable the hooks so we don't have to stub the GitLab API
      command: ["bash", "-c", "whoami; ls -l /srv/gitaly-ruby/git-hooks/; mkdir -p /home/git/repositories && rm -rf /srv/gitlab-shell/hooks/* && sudo rm -rf /srv/gitaly-ruby/git-hooks/* && exec /scripts/process-wrapper"]
      alias: gitaly
  variables:
    GITALY_ADDRESS: "tcp://gitaly:8075"
  script:
  - go version
  - make test

test using go 1.10:
  <<: *test_definition

test using go 1.11:
  image: golang:1.11
  <<: *test_definition

test:release:
  only:
    - tags
  script:
    - git describe --exact-match
